AgentBirbal/AgentBirbal/force-app/main/default/objects/Products_Purchased__c/Products_Purchased__c.object-meta.xml
<CustomObject>
    <label>Products Purchased</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>Product Purchased Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Purchased</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AgentBirbal/AgentBirbal/force-app/main/default/objects/Products_Purchased__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Product_Purchased</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AgentBirbal/AgentBirbal/force-app/main/default/classes/GetProdPurchasedApex.cls
public class GetProdPurchasedApex {
    @InvocableMethod(label = 'CaseSearch')
    public static List<List<String>> getCases(list<String> contactContxId){
        List<String> result = new List<String>();
        
        List<Products_Purchased__c> prodPurch = [SELECT Product_Name__c FROM Products_Purchased__c WHERE Contact__c=:contactContxId[0]];

        for(Products_Purchased__c c: prodPurch) {
            result.add(c.Product_Name__c);
        }
        
        return new List<List<String>>{result};
    }
}